print(" dan ".join(["asam","manis","pedaz"]))
print("ayam bakar".replace("bakar", "goreng"))
print("ayam bakar asam manis".startswith("ayam"))
print("ayam bakar asam manis".endswith("bakar"))
print("ayam bakar".upper())
print("Ayam Bakar".lower())
print("ayam bakar asam manis pedas".split())
print(min([14,15,17,20]))
print(max([14,15,17,20]))
print(round(14.52))
print(abs(-16.52))
print(sum([1,2,3,4,5,6,7]))
print(round(14.44))
